services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin123}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  f360taskapiemail:
    build:
      context: .
      dockerfile: F360Task.API/Dockerfile
    container_name: f360taskapiemail
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDB: ${MONGO_URI_EMAIL}
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Password: ${RABBITMQ_PASS:-guest}
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: Email
      RabbitMQ__Queue: EnviarEmail
      RabbitMQ__ConsumerTag: EnviarEmail
    networks:
      - backend

  f360taskapireport:
    build:
      context: .
      dockerfile: F360Task.API.Report/Dockerfile
    container_name: f360taskapireport
    ports:
      - "5010:8080"
      - "5011:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDB: ${MONGO_URI_REPORT}
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Password: ${RABBITMQ_PASS:-guest}
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: Report
      RabbitMQ__Queue: GerarReport
      RabbitMQ__ConsumerTag: GerarReport
    networks:
      - backend

  f360taskconsumeremail:
    build:
      context: .
      dockerfile: F360Task.Email.Consumer/Dockerfile
    container_name: f360taskconsumeremail
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDB: ${MONGO_URI_EMAIL}
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Password: ${RABBITMQ_PASS:-guest}
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: Email
      RabbitMQ__Queue: EnviarEmail
      RabbitMQ__ConsumerTag: EnviarEmail
    networks:
      - backend
    restart: unless-stopped

  f360taskconsumerreport:
    build:
      context: .
      dockerfile: F360Task.Report.Consumer/Dockerfile
    container_name: f360taskconsumerreport
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDB: ${MONGO_URI_REPORT}
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: ${RABBITMQ_USER:-guest}
      RabbitMQ__Password: ${RABBITMQ_PASS:-guest}
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: Report
      RabbitMQ__Queue: GerarReport
      RabbitMQ__ConsumerTag: GerarReport
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
