services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin123}
    volumes:
      - mongodb_data:/data/db

  # RabbitMQ with Management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  # API Email Service
  f360taskapiemail:
    build:
      context: .
      dockerfile: F360Task.API/Dockerfile
    container_name: f360taskapiemail
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: ${APP_ENV:-Development}
      ConnectionStrings__MongoDB: "mongodb+srv://projeto:projeto@cluster0.lif5jbi.mongodb.net/Email?retryWrites=true&w=majority&appName=Cluster0"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: "Email"
      RabbitMQ__Queue: "EnviarEmail"
      RabbitMQ__ConsumerTag: "EnviarEmail"

  # API Report Service
  f360taskapireport:
    build:
      context: .
      dockerfile: F360Task.API.Report/Dockerfile
    container_name: f360taskapireport
    ports:
      - "5010:80"
      - "5011:443"
    environment:
      ASPNETCORE_ENVIRONMENT: ${APP_ENV:-Development}
      ConnectionStrings__MongoDB: "mongodb+srv://projeto:projeto@cluster0.lif5jbi.mongodb.net/Email?retryWrites=true&w=majority&appName=Cluster0"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: "Report"
      RabbitMQ__Queue: "GerarReport"
      RabbitMQ__ConsumerTag: "GerarReport"

  # Email Consumer Service
  f360taskconsumeremail:
    build:
      context: .
      dockerfile: F360Task.Email.Consumer/Dockerfile
    container_name: f360taskconsumeremail
    environment:
      ASPNETCORE_ENVIRONMENT: ${APP_ENV:-Development}
      ConnectionStrings__MongoDB: "mongodb+srv://projeto:projeto@cluster0.lif5jbi.mongodb.net/Email?retryWrites=true&w=majority&appName=Cluster0"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: "Email"
      RabbitMQ__Queue: "EnviarEmail"
      RabbitMQ__ConsumerTag: "EnviarEmail"

  # Report Consumer Service
  f360taskconsumerreport:
    build:
      context: .
      dockerfile: F360Task.Report.Consumer/Dockerfile
    container_name: f360taskconsumerreport
    environment:
      ASPNETCORE_ENVIRONMENT: ${APP_ENV:-Development}
      ConnectionStrings__MongoDB: "mongodb+srv://projeto:projeto@cluster0.lif5jbi.mongodb.net/Email?retryWrites=true&w=majority&appName=Cluster0"
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Exchange: "Report"
      RabbitMQ__Queue: "GerarReport"
      RabbitMQ__ConsumerTag: "GerarReport"

volumes:
  mongodb_data:
